/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ReunionRouteImport } from './routes/reunion'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiOperationsRouteImport } from './routes/api/operations'
import { Route as ApiMeetingsRouteImport } from './routes/api/meetings'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiDocumentRequestsRouteImport } from './routes/api/document-requests'
import { Route as ApiApplicationsRouteImport } from './routes/api/applications'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin/applications.$id'

const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunionRoute = ReunionRouteImport.update({
  id: '/reunion',
  path: '/reunion',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationsRoute = ApiOperationsRouteImport.update({
  id: '/api/operations',
  path: '/api/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRoute = ApiMeetingsRouteImport.update({
  id: '/api/meetings',
  path: '/api/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentRequestsRoute = ApiDocumentRequestsRouteImport.update({
  id: '/api/document-requests',
  path: '/api/document-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsRoute = ApiApplicationsRouteImport.update({
  id: '/api/applications',
  path: '/api/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/admin/applications/$id',
  path: '/admin/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/confirmation': typeof ConfirmationRoute
  '/espace': typeof EspaceRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/resultats': typeof ResultatsRoute
  '/reunion': typeof ReunionRoute
  '/set-password': typeof SetPasswordRoute
  '/simulateur': typeof SimulateurRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/api/document-requests': typeof ApiDocumentRequestsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/operations': typeof ApiOperationsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/confirmation': typeof ConfirmationRoute
  '/espace': typeof EspaceRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/resultats': typeof ResultatsRoute
  '/reunion': typeof ReunionRoute
  '/set-password': typeof SetPasswordRoute
  '/simulateur': typeof SimulateurRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/api/document-requests': typeof ApiDocumentRequestsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/operations': typeof ApiOperationsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/confirmation': typeof ConfirmationRoute
  '/espace': typeof EspaceRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/resultats': typeof ResultatsRoute
  '/reunion': typeof ReunionRoute
  '/set-password': typeof SetPasswordRoute
  '/simulateur': typeof SimulateurRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/api/document-requests': typeof ApiDocumentRequestsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/operations': typeof ApiOperationsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/confirmation'
    | '/espace'
    | '/inscription'
    | '/login'
    | '/resultats'
    | '/reunion'
    | '/set-password'
    | '/simulateur'
    | '/admin/login'
    | '/api/applications'
    | '/api/document-requests'
    | '/api/files'
    | '/api/health'
    | '/api/leads'
    | '/api/meetings'
    | '/api/operations'
    | '/admin/'
    | '/admin/applications/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/confirmation'
    | '/espace'
    | '/inscription'
    | '/login'
    | '/resultats'
    | '/reunion'
    | '/set-password'
    | '/simulateur'
    | '/admin/login'
    | '/api/applications'
    | '/api/document-requests'
    | '/api/files'
    | '/api/health'
    | '/api/leads'
    | '/api/meetings'
    | '/api/operations'
    | '/admin'
    | '/admin/applications/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/confirmation'
    | '/espace'
    | '/inscription'
    | '/login'
    | '/resultats'
    | '/reunion'
    | '/set-password'
    | '/simulateur'
    | '/admin/login'
    | '/api/applications'
    | '/api/document-requests'
    | '/api/files'
    | '/api/health'
    | '/api/leads'
    | '/api/meetings'
    | '/api/operations'
    | '/admin/'
    | '/admin/applications/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ConfirmationRoute: typeof ConfirmationRoute
  EspaceRoute: typeof EspaceRoute
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  ResultatsRoute: typeof ResultatsRoute
  ReunionRoute: typeof ReunionRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SimulateurRoute: typeof SimulateurRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiApplicationsRoute: typeof ApiApplicationsRoute
  ApiDocumentRequestsRoute: typeof ApiDocumentRequestsRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiMeetingsRoute: typeof ApiMeetingsRoute
  ApiOperationsRoute: typeof ApiOperationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunion': {
      id: '/reunion'
      path: '/reunion'
      fullPath: '/reunion'
      preLoaderRoute: typeof ReunionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations': {
      id: '/api/operations'
      path: '/api/operations'
      fullPath: '/api/operations'
      preLoaderRoute: typeof ApiOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings': {
      id: '/api/meetings'
      path: '/api/meetings'
      fullPath: '/api/meetings'
      preLoaderRoute: typeof ApiMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-requests': {
      id: '/api/document-requests'
      path: '/api/document-requests'
      fullPath: '/api/document-requests'
      preLoaderRoute: typeof ApiDocumentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications': {
      id: '/api/applications'
      path: '/api/applications'
      fullPath: '/api/applications'
      preLoaderRoute: typeof ApiApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/admin/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ConfirmationRoute: ConfirmationRoute,
  EspaceRoute: EspaceRoute,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  ResultatsRoute: ResultatsRoute,
  ReunionRoute: ReunionRoute,
  SetPasswordRoute: SetPasswordRoute,
  SimulateurRoute: SimulateurRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiApplicationsRoute: ApiApplicationsRoute,
  ApiDocumentRequestsRoute: ApiDocumentRequestsRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiMeetingsRoute: ApiMeetingsRoute,
  ApiOperationsRoute: ApiOperationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
